### PR TITLE
Don't go through a giant table to find a few rags

### PR DESCRIPTION
**Pull request by mcNuggets1**
More optimized than before.

### CODE REVIEW

**Comment by mcNuggets1** [comment]
Just cached a table.

Useless reapplying the table in a think-hook.

**Comment by mcNuggets1** [comment]
You could add me in steam again as I removed you.

These changes are fine.
Going through a table with up to 8192 is stupid, but going over a table with max  64-128 entries is quite saving performance.

**Comment by MinIsMin** [comment]
Looks good, will test it later.

**Comment by mcNuggets1** [comment]
That can't break anything.
I actually want to commit more pull requests, but I am too stupid to do multiple.

**Comment by mcNuggets1** [comment]
Just found out there is a error everytime you shoot with a non css weapon

**Comment by markusmarkusz** [comment]
This doesn't really improve the performance. Afaik the difference is very very small.

**Comment by mcNuggets1** [comment]
Are you kidding me?
Going over a up to 8192 entries table every frame is not intense?

**Comment by mcNuggets1** [comment]
There are smarter ways of handling this however, I see.

**Comment by markusmarkusz** [comment]
I don't know why your table is that big.
ents.FindByClass iterates in C++ through the entities. I don't have any problems.
This could cause problems if OnEntityCreated/EntityRemoed fails somehow.
There are bigger performance issues in the SpecDM.

**Comment by mcNuggets1** [comment]
It iterates over all entities searching for entities with the same class.
Which would be in average about 600 entries on an ttt-server with about 12 players.

**Comment by markusmarkusz** [comment]
This is done in C++. I can't remember any laggs because of this function.
I'm sure you are not going to notice any big difference.

**Comment by mcNuggets1** [comment]
It's the same as using ents.GetAll(), but even more obsurd.

**Comment by markusmarkusz** [comment]
It's not the same.

**Comment by mcNuggets1** [comment]
So what in SpecDM does need alot of resources?

**Comment by markusmarkusz** [comment]
Loadout, BeginRound, some networking stuffs and perhaps the SpecDM HUD.

**Comment by mcNuggets1** [comment]
You're right, that's pretty unoptimized, atleast Loadout.

**Pull request merged**
