### PR TITLE
Don't play sounds of ghosts

### LINKED ISSUE #16: Burn
If you play on some MC Maps you can burn and interact with some objects.
Just a check for this to prevent this, would be good.

### PR DESCRIPTION
**Pull request by CSchulz**
Fixed #16

### CODE REVIEW

**Comment by markusmarkusz** [comment]
Noooooo!

**Comment by CSchulz** [comment]
Yes you are right. You have to notice if the player got burn damage and just then ignore the sound.

**Comment by markusmarkusz** [comment]
You can check if the entity is a valid ghost dm user and if the sound is a fire dmg sound.

**Comment by CSchulz** [comment]
So check the filename for ending with **burn.wav** should be okay, right?

**Comment by markusmarkusz** [comment]
Check the name of the sound.
For burn sounds it should be HL2Player.Burn or something like this.

**Comment by CSchulz** [comment]
@markusmarkusz Updated the condition.

PS: Send you an invitation on Steam.

**Pull request merged**
